### ISSUE TITLE
The settings menus are cropped in the dialog

### ISSUE THREAD

**Issue by tonydisera** [anderspitman/vue-pileup#1]
<img width="819" alt="screen shot 2018-10-25 at 4 24 22 pm" src="https://user-images.githubusercontent.com/8420103/47533867-9efc3400-d872-11e8-8ba7-871e0b30fe6c.png">

**Comment by anderspitman** [comment]
Interesting. I think the vuetify dialog must have overflow set to hidden. I'm not sure there's anything we can do about this directly, other than forcing the dialog to have enough extra space around it to handle all the menus, which I think would look ugly. I think the best thing would either be to just put up with it, or disable mouse interactions altogether (other than zooming and maybe other specific actions we can add buttons for). FYI those menu windows are draggable. Honestly I'm not sure I like providing the full functionality to the users, since igv is really a separate application.

**Comment by tonydisera** [comment]
Right now, I have added the following style to move the settings glyphs to the left so that the menus don't crop:
  .igv-right-hand-gutter
    right: initial
    left: 0px

It would probably be better to add this to your vue component.

**Comment by anderspitman** [comment]
I agree. How about I hide the settings altogether within vue-pileup?

**Comment by anderspitman** [comment]
Fixed in #9
